# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ci_pb2 as ci__pb2


class GreeterStub(object):
    """The greeting service definition.
    """
    
    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTest = channel.unary_unary(
                '/c_ci.Greeter/CallTest',
                request_serializer=ci__pb2.TestRequest.SerializeToString,
                response_deserializer=ci__pb2.TestReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def CallTest(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTest': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTest,
                    request_deserializer=ci__pb2.TestRequest.FromString,
                    response_serializer=ci__pb2.TestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'c_ci.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def CallTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/c_ci.Greeter/CallTest',
            ci__pb2.TestRequest.SerializeToString,
            ci__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
