# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ci.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63i.proto\x12\x04\x63_ci\"\x1b\n\x0bTestRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1b\n\tTestReply\x12\x0e\n\x06retMsg\x18\x01 \x01(\t2;\n\x07Greeter\x12\x30\n\x08\x43\x61llTest\x12\x11.c_ci.TestRequest\x1a\x0f.c_ci.TestReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ci_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREQUEST._serialized_start=18
  _TESTREQUEST._serialized_end=45
  _TESTREPLY._serialized_start=47
  _TESTREPLY._serialized_end=74
  _GREETER._serialized_start=76
  _GREETER._serialized_end=135
# @@protoc_insertion_point(module_scope)
